// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: role.sql

package database

import (
	"context"
)

const createRole = `-- name: CreateRole :one
INSERT INTO role(rolename, registeredby)
VALUES($1, $2)
RETURNING roleid, rolename, registeredby, registereddate
`

type CreateRoleParams struct {
	Rolename     string
	Registeredby string
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRowContext(ctx, createRole, arg.Rolename, arg.Registeredby)
	var i Role
	err := row.Scan(
		&i.Roleid,
		&i.Rolename,
		&i.Registeredby,
		&i.Registereddate,
	)
	return i, err
}
